services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ./caddy/init/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/init/site:/srv
      - caddy_data:/data
      - caddy_config:/config
      - ssl-auto-recorder-data:/srv/recordings:ro
    networks:
      - expose

  guacd:
    image: guacamole/guacd:1.5.5
    restart: unless-stopped
    volumes:
      - guacd-drive:/drive:rw
      - guacd-record:/record:rw
    networks:
      - guacamole
      - match

  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD:
      POSTGRES_USER: guacamole_user
    ports:
      - "5432/tcp"
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d:ro
      - postgres-data:/var/lib/postgresql/data:rw
    networks:
      - guacamole

  guacamole:
    image: guacamole/guacamole:1.5.5
    restart: unless-stopped
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_USER: guacamole_user
    depends_on:
      - guacd
      - postgres
    ports:
      - "8080/tcp" # Guacamole is on :8080/guacamole, not /.
    networks:
      - guacamole
      - expose

  ssl-vision-client:
    image: robocupssl/ssl-vision-client:1.8.3
    command: [ "-visionAddress", "224.5.23.2:10020" ]
    restart: unless-stopped
    ports:
      - "8082/tcp"
    networks:
      - match
      - expose

  ssl-status-board:
    image: robocupssl/ssl-status-board:2.11.8
    restart: unless-stopped
    ports:
      - "8082/tcp"
    networks:
      - match
      - expose

  ssl-game-controller:
    image: robocupssl/ssl-game-controller:3.13.1
    command:
      - "-visionAddress"
      - "224.5.23.2:10020"
      - "-trackerAddress"
      - "224.5.23.2:10010"
      - "-publishAddress"
      - "224.5.23.1:10003"
      - "-address"
      - ":8081"
    restart: unless-stopped
    volumes:
      - ssl-game-controller-config:/config:rw
    ports:
      - "8081/tcp"
    networks:
      - match
      - expose

  simulator:
    image: roboticserlangen/simulatorcli:commit-6a4e1c06533b
    #    image: robocupssl/grsim:2.4.0
    restart: unless-stopped
    environment:
      # ER-Force options
      GEOMETRY: "2020"
      REALISM: "RC2021"
    ports:
      - "10300/udp"
      - "10301/udp"
      - "10302/udp"
    networks:
      - match

  ssl-simulation-controller:
    image: robocupssl/ssl-simulation-controller:0.13.0
    command:
      - "-refereeAddress"
      - "224.5.23.1:10003"
      - "-visionAddress"
      - "224.5.23.2:10020"
      - "-trackerAddress"
      - "224.5.23.2:10010"
      - "-simControlPort"
      - "10300"
      - "-robotSpecConfig"
      - "/config/robot-specs.yaml"
    restart: unless-stopped
    volumes:
      - ./config/ssl-simulation-controller:/config:ro
    networks:
      - match

  ssl-auto-recorder:
    image: robocupssl/ssl-auto-recorder:1.8.3
    restart: unless-stopped
    volumes:
      - ssl-auto-recorder-data:/data:rw
    networks:
      - match

  # Maintainer is a container for the maintainers of the event for testing purposes
  maintainer:
    image: robocupssl/ubuntu-vnc-go:latest
    restart: unless-stopped
    mem_limit: 2g
    cpus: 2
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - maintainer-data:/home/default:rw
      - ssl-auto-recorder-data:/ssl-auto-recorder-data:rw
      - ssl-game-controller-config:/ssl-game-controller-config:rw
    ports:
      - "5901/tcp"
      - "2222/tcp"
    networks:
      - match
      - guacamole

  autoref-tigers:
    # Run without UI in active mode
    image: tigersmannheim/auto-referee:1.5.5
    command: [ "-hl", "-a", "--visionAddress", "224.5.23.2:10020" ]
    # Run with UI (note: need to connect to the UI once to start the autoRef)
    # image: tigersmannheim/auto-referee-vnc:1.5.2
    # command: [ "vnc", "-a" ]
    restart: unless-stopped
    environment:
      - VNC_PASSWORD=${VNC_PW}
    ports:
      - "5900/tcp"
    networks:
      - match
      - guacamole

  autoref-erforce:
    image: roboticserlangen/autoref:2025.0.0
    # Run with UI (note: need to connect to the UI once to start the autoRef)
    # command: [ "vnc" ]
    command: [ "--vision-port", "10020" ]
    restart: unless-stopped
    environment:
      - VNC_PASSWORD=${VNC_PW}
    ports:
      - "5900/tcp"
    networks:
      - match
      - guacamole

volumes:
  caddy_data:
  caddy_config:
  guacd-drive:
  guacd-record:
  postgres-data:
  ssl-game-controller-config:
  maintainer-data:
  ssl-auto-recorder-data:

networks:
  expose:
  match:
  guacamole:
