version: '2.4'

services:
  caddy:
    image: caddy:2-alpine@sha256:b60636634fd2aebaf9460cf60997ad83aad6b139318d5713e2b78a60f52b139c
    restart: unless-stopped
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ./caddy/init/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/init/site:/srv
      - caddy_data:/data
      - caddy_config:/config
      - ssl-auto-recorder-data:/srv/recordings:ro
    networks:
      - expose

  guacd:
    image: guacamole/guacd:1.5.4@sha256:8a6fd083213053cd0217663c24ab59245ebfe442b6717e606ebea25707ace650
    restart: unless-stopped
    volumes:
      - guacd-drive:/drive:rw
      - guacd-record:/record:rw
    networks:
      - guacamole
      - match

  postgres:
    image: postgres:16@sha256:557fea37a744d5f4c8faab304b0a90858b53ab119735a88c131fd19dab802f36
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD:
      POSTGRES_USER: guacamole_user
    ports:
      - 5432/tcp
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d:ro
      - postgres-data:/var/lib/postgresql/data:rw
    networks:
      - guacamole

  guacamole:
    image: guacamole/guacamole:1.5.4@sha256:a7763a8057036c12b4fde8a6725e5200a434aa74f0a4cff726e70718ee4521b4
    restart: unless-stopped
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD:
      POSTGRES_USER: guacamole_user
    depends_on:
      - guacd
      - postgres
    ports:
      - 8080/tcp # Guacamole is on :8080/guacamole, not /.
    networks:
      - guacamole
      - expose

  ssl-vision-client:
    image: robocupssl/ssl-vision-client:1.7.3@sha256:265f8cc1c620a9d83224b739e605abc8a4ffef4e75735047999e16e21a577e79
    command: [ "-visionAddress", "224.5.23.2:10006" ]
    restart: unless-stopped
    ports:
      - 8082/tcp
    networks:
      - match
      - expose

  ssl-status-board:
    image: robocupssl/ssl-status-board:2.10.4@sha256:74a5eef17dbf34ec88b4061c31ce6e492188380c9568cd7f4c6f314de02b7583
    restart: unless-stopped
    ports:
      - 8082/tcp
    networks:
      - match
      - expose

  ssl-game-controller-private:
    image: robocupssl/ssl-game-controller:3.9.0@sha256:2511cd0a2c9ff4cb7fd5d1ee7b32a457b6c6fc10276d0d2ce5ba07f894c85451
    command:
      - "-visionAddress"
      - "224.5.23.2:11006"
      - "-trackerAddress"
      - "224.5.23.2:11010"
      - "-publishAddress"
      - "224.5.23.1:11003"
      - "-address"
      - ":8081"
    restart: unless-stopped
    volumes:
      - ssl-game-controller-config:/config:rw
    ports:
      - 8081/tcp
    networks:
      - referee
      - expose

  ssl-game-controller-public:
    image: g3force/proxy-tcp-udp-mc:0.2.1@sha256:05b342dfd63c57080c8225a2faa89164cf5b1bdeed58a904b8300ae078edfc6f
    command:
      - "tcp,:10007,ssl-game-controller-private:10007,AutoRef"
      - "tcp,:10008,ssl-game-controller-private:10008,Team"
      - "tcp,:10011,ssl-game-controller-private:10011,RemoteCtrl"
      - "mc,224.5.23.1:11003,224.5.23.1:10003,Referee"
      - "mc,224.5.23.2:10006,224.5.23.2:11006,Vision"
      - "mc,224.5.23.2:10010,224.5.23.2:11010,Tracker"
    restart: unless-stopped
    ports:
      - 10007/tcp
      - 10008/tcp
      - 10011/tcp
    networks:
      - referee
      - match

  simulator-private:
    image: roboticserlangen/simulatorcli:commit-6a4e1c06533b@sha256:19d0df91697c82ebfd1f86eca5ccf6b8be2f0d64b22078725257c3a5856b5ddc
#    image: robocupssl/grsim:2.4.0
    restart: unless-stopped
    environment:
      # ER-Force options
      GEOMETRY: "2020"
      REALISM: "RC2021"
    ports:
      - 10300/udp
      - 10301/udp
      - 10302/udp
    networks:
      - simulator

  simulator:
    image: g3force/proxy-tcp-udp-mc:0.2.1@sha256:05b342dfd63c57080c8225a2faa89164cf5b1bdeed58a904b8300ae078edfc6f
    command:
      - "udp,:10301,simulator-private:10301,Blue"
      - "udp,:10302,simulator-private:10302,Yellow"
      - "mc,224.5.23.2:10020,224.5.23.2:10006,Vision"
      - "mc,224.5.23.1:10003,224.5.23.1:11003,Referee"
      - "mc,224.5.23.2:10010,224.5.23.2:11010,Tracker"
    restart: unless-stopped
    ports:
      - 10300/udp
      - 10301/udp
      - 10302/udp
    networks:
      - simulator
      - match

  ssl-simulation-controller:
    image: robocupssl/ssl-simulation-controller:0.12.1@sha256:7765761a838da09289e0039d54d21fc3ca37bcf124dd15749ee416f440c92067
    command:
      - "-refereeAddress"
      - "224.5.23.1:11003"
      - "-visionAddress"
      - "224.5.23.2:10020"
      - "-trackerAddress"
      - "224.5.23.2:11010"
      - "-simControlPort"
      - "10300"
      - "-robotSpecConfig"
      - "/config/robot-specs.yaml"
    restart: unless-stopped
    volumes:
      - ./config/ssl-simulation-controller:/config:ro
    networks:
      - simulator

  ssl-auto-recorder:
    image: robocupssl/ssl-auto-recorder:1.5.2@sha256:b2aad304b99b30c2de272756c30523826bb6fe8beb003efd7a0b4dc9b5318988
    restart: unless-stopped
    volumes:
      - ssl-auto-recorder-data:/data:rw
    networks:
      - match

  # Maintainer is a container for the maintainers of the event for testing purposes
  maintainer:
    image: robocupssl/ubuntu-vnc-go:latest@sha256:c14dce09b856fd3a08e27bff8109c3ea8bc6260de721e9fe6a82cda6c638954c
    restart: unless-stopped
    mem_limit: 2g
    cpus: 2
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - maintainer-data:/home/default:rw
      - ssl-auto-recorder-data:/ssl-auto-recorder-data:rw
      - ssl-game-controller-config:/ssl-game-controller-config:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  autoref-tigers:
    image: tigersmannheim/auto-referee:1.2.0@sha256:34d74deee2140e9fc2b8549f156422ccc2213969e33463ed23444543c6b120d7
    # Run with UI (note: need to connect to the UI once to start the autoRef)
    # command: [ "vnc", "-a" ]
    # Run without UI in active mode
    command: [ "-a" ]
    restart: unless-stopped
    environment:
      - VNC_PASSWORD=${VNC_PW}
    ports:
      - 5900/tcp
    networks:
      - match
      - guacamole

  autoref-erforce:
    image: roboticserlangen/autoref:commit-6f15f574ea80@sha256:3d7c5933c12eb193a1fefcfd6aba86fba42875c588cc883dc20d0bfcb66b11cb
    # Run with UI (note: need to connect to the UI once to start the autoRef)
    # command: [ "vnc" ]
    restart: unless-stopped
    environment:
      - VNC_PASSWORD=${VNC_PW}
    ports:
      - 5900/tcp
    networks:
      - match
      - guacamole

volumes:
  caddy_data:
  caddy_config:
  guacd-drive:
  guacd-record:
  postgres-data:
  ssl-game-controller-config:
  maintainer-data:
  ssl-auto-recorder-data:

networks:
  expose:
  match:
  simulator:
  referee:
  guacamole:
